### ISSUE TITLE
Loading content from `config` branch fails

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#158]
this is a variation of: https://github.com/adobe/helix-simulator/issues/151

hlx up doesnt work in a branch named `config`

```
$ hlx up
...
[git] info: [72420] HTTP: listening on port 63905
[hlx] error: Could not find Markdown at http://127.0.0.1:63905/raw/helix/content/config/index.md
...
...
$ git br -m config foo
...
...
$ hlx up
...
(works)
```

**Comment by tripodsan** [comment]
caused by https://github.com/adobe/git-server/issues/55

**Comment by stefan-guggisberg** [comment]
It's an `isomorphic-git` bug:
* https://github.com/isomorphic-git/isomorphic-git/issues/709
* https://github.com/isomorphic-git/isomorphic-git/pull/710

For the time being, if possible, avoid the following branch names:
`config`, `description`, `index`, `shallow`, `commondir`
