### ISSUE TITLE
json pipeline is not usable

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-simulator#169]
1. Create a `json.htl` with content:

```
${content}
```

2. Create a `json.pre.js` with content: 

```
function pre(payload, action) {
  payload.content = JSON.stringify(payload.content);
}

module.exports.pre = pre;
```

3. Run `hlx up` and request http://localhost:3000/index.json

According to the code, this should work but it only outputs:

```
[object Object]
```

Expected: the payload content should be rendered.

A first debugging session revealed that this line is the issue: https://github.com/adobe/helix-simulator/blob/master/src/HelixServer.js#L191
Removing that line fixes the issue.

Removing the `stringify` in the `pre.js` does not solve the pb (should not be necessary from my pov).

More analysis required.

**Comment by kptdobe** [comment]
There is no integration tests of the json pipeline thus the regression was introduced and never caught.

**Comment by tripodsan** [comment]
i think the json pipeline should not use the pipeline at all. just a `json.js`

**Comment by tripodsan** [comment]
or, override the content yep on your pre.js

**Comment by kptdobe** [comment]
My use case is pretty simple: I want to output the `sections` part of the content as json to visualise it better (my browser has a nice json formatter).

I need the pipeline because it needs to fetch the md, compute the sections, set the content type... this is all done already by https://github.com/adobe/helix-pipeline/blob/master/src/defaults/json.pipe.js which is fine. Just a matter of finding how to use it and make sure it does what it is supposed to do.

My basis sample where I want to output the full `payload.content` should only require the `json.htl` file I think, the `json.pre.js` is only there to `stringify` in my case but it should not be necessary. 
I think the pb is coming from the htl instruction which is doing a "to string" on the object. I do not think there is an alternative to that.

**Comment by tripodsan** [comment]
Yes. But set the response type to text/htm. The problem is not in the simulator,  it mimicks what ooenwhisk is doing. I.e try to deploy your action  and see if it behaves the same.

**Comment by tripodsan** [comment]
If you need the pipeline in your `Json.js` you need to import and construct the pipeline yourself

**Comment by kptdobe** [comment]
humm... why ? everything is (almost) there! The only issue is that line you introduced with https://github.com/adobe/helix-simulator/commit/f3a9c22b49ec2548e5d17db8e4678efa02efd27e#diff-8810b7a024e44b8ee8d9f6f49ca74ff1R146
which btw, seems unrelated to the issue. If I remove that line, I do not need to construct anything by myself, at least this is my assumption when I read the code. @trieloff built the json pipeline.
I think the `json.htl` and the `json.pre.js` are the way to go to define what do you want to output.

**Comment by tripodsan** [comment]
As I said. I'm pretty sure this is how ooenwhisk does it. It strungyfues the object.

**Comment by tripodsan** [comment]
Having a `json.htl` outputting a string sound like a big hack.

**Comment by kptdobe** [comment]
Me too. I am just trying to use what has been built and is not working as expected (or I do not know how to use).
If you do not have the `json.htl` file, you do not have a template thus it is not rendered. Also, how would you determine what json object do you want to output ?

**Comment by tripodsan** [comment]
I just tested it again. it's quite simple. just create a `json.js`:

```js
module.exports.main = (payload, action) => {
  return {
    response: {
      body: payload
    }
  };
};
```

and everything works!

**Comment by kptdobe** [comment]
aaaaahhhh....!

I inspired for @rofe's code here: https://github.com/adobe/developer.adobe.com/blob/master/src/sitemap_xml.js#L55

I did not pay attention to the `async`. Obviously, this does not work!

Thanks!

**Comment by tripodsan** [comment]
> I did not pay attention to the async. Obviously, this does not work!

?? yes. `async` works,

**Comment by kptdobe** [comment]
yes, now it works. I really do not understand. I had that code multiple times (my local history confirms) but it did not work. I really do not get it...

**Comment by rofe** [comment]
One of the differences between `json` and `xml` pipe is that the latter explicitly [emits](https://github.com/adobe/helix-pipeline/blob/master/src/xml/emit-xml.js) the XML after the main function, using the object in `content.xml`. Much like the `html` pipe emits HTML based on `content.document`. This gives developers control over the output, and to be honest, I would expect the `json` pipe to work similarly... 🤔

**Comment by kptdobe** [comment]
I think it is all good now., even though I am still confused how this is supposed to work.

I thought that using the `main` function will override the full pipeline, i.e. you can handle the whole process and have to deal with the fetch and md processing. But that's not the case. Using a `<selector>_json.js` still calls the `json.pipe.js` and the payload you get is the one I expect with the md processing. Same applies with for the `xml` and the `xml.pipe.js` I assume.
In the end, this seems to be similar than the `pre.js` and ` .htl` combinaison except that you do not control the output via the `.htl` template but you must define a `response.body` in your payload.

**Comment by kptdobe** [comment]
I assume also that if you want a complete custom pipeline, you need to define a `<extension>.pipe.js` in your project. Here you can do whatever you want.

**Comment by kptdobe** [comment]
If this is all correct, I write some specific tests and documentation for all of that. Because it is not so... obvious ;)

**Comment by tripodsan** [comment]
yes. this is all correct.

we decided at the last-last hackathon, that the pure `.js` actions, aka. CGIs, will reside in `htdocs/cgi-bin`. but those aren't implemented yet. see https://github.com/adobe/helix-cli/issues/436

**Comment by kptdobe** [comment]
ok. The link between "pure-action" and "custom pipeline" was not so obvious. Got it now, thanks.

**Comment by rofe** [comment]
> Same applies with for the `xml` and the `xml.pipe.js` I assume.

Not quite: the `content.xml` property isn't written by default. What should be the default XML output? Because we can't know for sure (the example above was sitemap.xml) we decided to leave it up to the user to construct `content.xml` based on the payload.

**Comment by kptdobe** [comment]
But that's the same for the `json` one: no output by default. You must define the output in the `main`.

**Comment by rofe** [comment]
Exactly. Which is probably ok because it's not simple to anticipate what the default output should be for both JSON and XML. But the difference is that there is a defined `content.xml` object property (API?) to be used for rendering in the `xml` pipe, whereas in the `json` pipe, you manually handle the emission by directly writing the `response.body`. Might be confusing for developers...

@trieloff, @koraa wdyt?
