### ISSUE TITLE
Awesome error messages

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-simulator#17]
Let's make sure the error messages shown in the browser during development are really good.

I'd like to see:

- request dump (all headers and cookies)
- full stack trace
- code preview for all project code (resolve source maps, too)
- log messages from current request

**Edit**: something like [Whoops](https://github.com/filp/whoops) would be ideal.

![](
https://camo.githubusercontent.com/31a4e1410e740fd0ccda128cbcab8723f45e7e73/687474703a2f2f692e696d6775722e636f6d2f305651706539362e706e67)

**Comment by trieloff** [comment]
Here's the other issue @kamendola

**Comment by trieloff** [comment]
Adobe/hypermedia-pipeline#61 will be useful here

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rofe** [comment]
@kamendola can you add or link to the mockups?
