### ISSUE TITLE
Proxy strains does not work on URL path

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#213]
Still seeing the same issue w/ helix-cli 2.1.6.

Relevant helix config part:

```
  - name: support-staging
    origin: https://adobedocs.github.io/developer-support/
    url: https://adobedevsite.helix-demo.xyz/support
```

Run `hlx up --host adobedevsite.helix-demo.xyz --local-repo=.`, then load http://localhost:3000/support

Get a 404 page, and `hlx up` output says:

```
[hlx] info: Proxy GET request to https://adobedocs.github.io:443/support
```

The expectation is that `hlx up` output would provide the correct path to the github.io URL.

_Originally posted by @filmaj in https://github.com/adobe/helix-publish/issues/64#issuecomment-491016126_

**Comment by filmaj** [comment]
Confirmed seems to work in 2.5.0.

**Comment by hirenoble** [comment]
Thank you everyone!!
