### ISSUE TITLE
ESI include: query string with multiple parameters not properly supported

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-simulator#245]
In the `html.htl`, try:

```
<esi:include src="https://www.google.com/search?q=test&ie=UTF-8" />
```

and 

```
<esi:include src="https://www.google.com/search?ie=UTF-8&q=test" />
```

They should lead to the same result but they don't: in the second case, the `test` query is not received by Google and just show the homepage instead of the search results.
Initial debugging revealed the issue: the ESI module does not properly deal with the `&` character: in both cases, the second query parameter will start with a `amp;`.

**Comment by trieloff** [comment]
There are two issues happening:

- the DOM-based HTL-serializer inserts `&amp;` (something it didn't do before)
- and nodesi does not deal with the `&amp;` in the correct way https://github.com/Schibsted-Tech-Polska/nodesi/issues/17

the right place to fix this is here: https://github.com/Schibsted-Tech-Polska/nodesi/issues/17

**Comment by kptdobe** [comment]
To be verified since the PR has been merged.
