### ISSUE TITLE
<esi:remove> are not... removed!

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-simulator#292]
1. Run `hlx demo && cd demo`
1. Create a `foo.md` file and insert some content
1. Insert `` `markdown:foo.md` `` or `` `markdown:/foo.html` `` inside `index.md` of a project.
1. Add a `embed_html.htl` script to the project with content: `${content.document.body}` (just dump the body of the embedded document)
1. Run `hlx up` -> the page contains the `foo.md` file content but also an HTML tag `<esi:remove><code>markdown:foo.md</code></esi:remove>` which is visible.

**Comment by tripodsan** [comment]
does Fastly support the `<esi:remove>` tag?

**Comment by kptdobe** [comment]
I think so, but I am not 100% sure. For https://github.com/adobe/helix-pipeline/issues/461, I published a site, the includes are broken but no `esi:remove` tags present in the generated source.

**Comment by kptdobe** [comment]
I tested, Fastly removes them.

**Comment by kptdobe** [comment]
PR merge and released in nodesi v1.12.1.
Waiting for dependency update to verify this is fixed as expected.

**Comment by tripodsan** [comment]
@kptdobe any news?

**Comment by kptdobe** [comment]
This was resolved with 5be9130dd241f874760673308d7e3933c422b0cc (include of nodesi v1.12.1).
