### ISSUE TITLE
Buffer argument in res.send() is not understood by nodesi

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-simulator#377]
In:

https://github.com/adobe/helix-simulator/blob/c1154a2019cfc1613c7a2c5d80fff8681b42ac35/src/HelixServer.js#L257

a Buffer is sent down to the next handler, which happens to be `nodesi`. This will not accept anything but a string:
```
if(typeof body === 'string' && !req._esiProcessed) {
  esi.process(body, req.esiOptions).then(oldSend);
}
```
so ESI does not work with the simulator.

**Comment by tripodsan** [comment]
> so ESI does not work with the simulator.

ESI in static responses are not expanded in the simluator...

**Comment by dominique-pfister** [comment]
Created a PR for nodesi instead: https://github.com/Schibsted-Tech-Polska/nodesi/issues/30
