### ISSUE TITLE
Querystring parameters are not available as key value pairs in params but as string in params.params

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-simulator#378]
If I write an action that takes a parameter e.g. `page`, and reference it in my action body:
```
const { page } = params;
```
it will work in OpenWhisk, but not when accessed via simulator where I have to declare it as follows:
```
const { page } = require('querystring').parse(params.params);
```

**Comment by tripodsan** [comment]
this should only be true for actions in cgi-bin, but not for normal pre.js actions.
