### ISSUE TITLE
Implement Aloglia Proxy similar to VCL

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#385]
As a developer, I expect helix queries to work similar they do on the edge.

the VCL on edge proxies queries to algolia, this was added here:
  https://github.com/adobe/helix-publish/pull/288/files

**Comment by tripodsan** [comment]
@stefan-guggisberg do you want to tackle this as well ?

**Comment by stefan-guggisberg** [comment]
fixed via #389
