### ISSUE TITLE
Proxies should not be redirects

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-simulator#387]
See #386 which is implemented as a client-side redirect. A cleaner implementation would be a server-side reverse proxy for this and similar requests such as blob store or Algolia queries.

**Comment by tripodsan** [comment]
either similar to:
https://github.com/adobe/helix-simulator/blob/b71631b14062118ae01f14cebdcb9375c0553b60/src/HelixServer.js#L193

or maybe use [express-http-proxy](https://www.npmjs.com/package/express-http-proxy)

**Comment by stefan-guggisberg** [comment]
fixed via #390
