### ISSUE TITLE
add support for .pngs for hlx_* resources

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-simulator#395]
i am not sure that this is the right place but it looks like the png handling doesn't seem to work properly when going through the simulator. a quick way to reproduce is to copy/paste and png into a google doc and then try to request the respective page in simulator.
the process seems to work fine outside of simulator albeit with a somewhat misleading `.jpg` extension for the image.

**Comment by tripodsan** [comment]
works for me....

**Comment by davidnuescheler** [comment]
yup, sorry, i was running an old version of `helix-cli` locally... sorry for the noise.
