### ISSUE TITLE
simulator still seems to send 404 for /hlx_<hash>.mp4

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-simulator#523]
it looks like the simulator still sends `404` for `/hlx_<hash>.mp4` requests, possibly for others.
compare: 

https://blog.adobe.com/hlx_e17afbb12dffda6a0dbe05436b5464819f64a9c2.mp4 

vs 

http://localhost:3000/hlx_e17afbb12dffda6a0dbe05436b5464819f64a9c2.mp4

**Comment by tripodsan** [comment]
should be fixed with https://github.com/adobe/helix-simulator/pull/530
