### ISSUE TITLE
XSLX rendering: JSON response is not structured the same with the simulator

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-simulator#545]
Run:

```
git clone https://github.com/adobe/theblog
cd theblog
git checkout xlsx-taxonomy
hlx up
```

Now request: http://localhost:3000/en/topics/_taxonomy.json
Response looks like:

```
[{
...
}]
```

Compare to helix-pages rendering of the same resource: https://xlsx-taxonomy--theblog--adobe.hlx.page/en/topics/_taxonomy.json

```
[{
data: [{...}]
limit: 143
offset: 0
total: 143
}]
```

This is so error prone!

cc @tripodsan

**Comment by tripodsan** [comment]
@kptdobe https://github.com/adobe/theblog has no branch with this name...

**Comment by tripodsan** [comment]
I guess you have an old simulator. the query index is also excel based, and it returns the correct result:

```
http://localhost:3000/en/query-index.json?offset=0&limit=10
```

**Comment by kptdobe** [comment]
Ahhh... I confirm that updating to latest cli fixes the issue... thanks for checking and sorry for the noise ;)
