### ISSUE TITLE
hlx_fonts loading errors trigger a lot of 404

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-simulator#549]
When I work with the simulator on the adobe/theblog project, I get a lot of 404 which wake up frequently our High Error Frequency check: https://helix.coralogix.com/#/query/logs?id=vYmDcn6Y14Yp6yrZuDd2WL

75% of those errors seem to be related to /hlx_fonts files (like http://localhost:3000/hlx_fonts/af/507e89/00000000000000003b9aee49/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i4&v=3)

Interestingly when working on the hlx.page version of the site for the same project branch, the same url works fine.

Looking at some of those log entries, I can observe:

My localhost request `http://localhost:3000/hlx_fonts/af/507e89/00000000000000003b9aee49/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=i4&v=3` (404)

appears on Fastly as: 

```
{
   "cdn":
    {
     "url"  :  "https://landingpage--theblog--adobe.hlx.page/hlx_fonts/af/507e89/00000000000000003b9aee49/27/l.html" ,
     ...
    },
     "request"  : {
       "id"  :  "a679be30-c0f4-f4bd-a5ab-56ef77f16bd7" ,
       "method"  :  "GET" ,
       "protocol"  :  "HTTP/1.1" ,
       "h2"  :  false ,
       "h2_push"  :  false ,
       "is_ipv6"  :  false ,
       "h2_stream_id"  :  "0" ,
       "url"  :  "/hlx_fonts/af/507e89/00000000000000003b9aee49/27/l.html" ,
       "referer"  :  "http://localhost:3000/" ,
```

Requesting the same URL directly https://landingpage--theblog--adobe.hlx.page/hlx_fonts/af/507e89/00000000000000003b9aee49/27/l.html works fine.

I assume the "referer" to be the issue. I assume the simulator should update the referer before making the request to hlx.page or maybe this is in the content-proxy ?

@tripodsan @trieloff WDYT ?

**Comment by trieloff** [comment]
The request type is "Fonts" so the content proxy is not involved. If it's indeed the referrer, I see two ways to fix it:
- as you suggested, by proxying through the simulator and adding the referer there
- by checking the referer in VCL and changing `localhost:3000` to the current domain

**Comment by tripodsan** [comment]
why has the url a `.html` ?
```
     "url"  :  "https://landingpage--theblog--adobe.hlx.page/hlx_fonts/af/507e89/00000000000000003b9aee49/27/l.html" ,
```

**Comment by tripodsan** [comment]
I think the simulator drops the query.....

https://github.com/adobe/helix-simulator/blob/4b2851fa52f996ca82277e097d312b88a7d6aeaa/src/HelixServer.js#L275-L279

**Comment by tripodsan** [comment]
btw: there is no `landingpage` branch....
