### ISSUE TITLE
Better openwhisk emulation

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#59]
helix-simulator should use the same set of libraries than the openwhisk container where the action runs.

suggestion:
- improve the custom docker container package with an _action executor_
- in helix-simulator, execute the compiled scripts via that executor instead directly in server.

**Comment by tripodsan** [comment]
one possibility would be to [fork](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) the openwhisk action emulator for each script. and use some IPC for transporting the logfile. the problem will be to attach another debugger to that process.

**Comment by tripodsan** [comment]
it might also be possible to isolate the module paths by tweaking `Module._nodeModulePaths` to only use the ones defined in the _action executor_

**Comment by trieloff** [comment]
> and use some IPC for transporting the logfile.

As we are using the Loggly service for logging inside the container anyway, why don't we override the host host with a local emulator, so that logging happens via HTTP?

**Comment by tripodsan** [comment]
...so we also need a loggly-emulator...

**Comment by trieloff** [comment]
Don't imitate, emulate. 😀

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
