### ISSUE TITLE
Wrong request params in simulator

### ISSUE THREAD

**Issue by rofe** [adobe/helix-simulator#613]
**Description**
When running the simulator (`--no-pages-proxy`) on a repo `https://github.com/myorg/myrepo`, the `action.request.params` look like this:
```js
{
  owner: "helix",
  repo: "github.com--myorg--myrepo",
  ref: "main",
  ...
}
```

**Expected behavior**
```js
{
  owner: "myorg",
  repo: "myrepo",
  ref: "main",
  ...
}
```

**Version:**
13.3.13

**Comment by tripodsan** [comment]
@rofe A fix for this is not possible. we cannot change the git coordinates to the real github, otherwise it defeats the purpose of local development.
