### ISSUE TITLE
local development with longs urls might fail

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#625]
local dev with very longs urls directly hit the inner cdn and might product errors.
this can happen for very long request parameters. since those are not used serverside, they can be removed when fetching the source.

requests again the following pattern can be stripped:

```
NOT /hlx_* AND NOT */media_* AND NOT .json AND NOT /cgi-bin/*
```

**Comment by trieloff** [comment]
You can strip all other request parameters (except cgi-bin) too, we strip most non `hlx_*` parameters from the URL.
