### ISSUE TITLE
Rename to `helix-simulator`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#79]
suggest to use a less _funny_ name for this package and repository.

suggest
--------
- `helix-server`
- `helix-dev`
- `helix-sim`
- `helix-simulator`

**Comment by trieloff** [comment]
+1 `helix-simulator`

`helix-server` sounds too production-like.

**Comment by stefan-guggisberg** [comment]
+0.5 for `helix-simulator`

how about `helix-local-server`?

**Comment by tripodsan** [comment]
I agree with @trieloff  to avoid the name server... however, maybe we need a 'server' at some point for live-preview and realtime collaboration. :-)

**Comment by trieloff** [comment]
I can live with `helix-local-server`, so that's another +1 from me.

**Comment by kptdobe** [comment]
`helix-serverless` ? :)

I am fine with all the options exception `helix-server`

**Comment by tripodsan** [comment]
let's avoid the term `server` for now and go with `helix-simulator`.

@davidnuescheler  any opinion on this?

**Comment by tripodsan** [comment]
can you rename the repo, @trieloff, I'll rename the packages later.

**Comment by stefan-guggisberg** [comment]
i went ahead and renamed it.

**Comment by tripodsan** [comment]
senks

**Comment by tripodsan** [comment]
@trieloff  do you have karma to rename the project in LGTM ? https://lgtm.com/projects/g/adobe/petridish/

**Comment by trieloff** [comment]
I don't know renaming is possible. Maybe @sjvs has an idea.

**Comment by sjvs** [comment]
Let me check my karma levels...

**Comment by sjvs** [comment]
All done: https://lgtm.com/projects/g/adobe/helix-simulator (works for me, but if you get a 404 then it's probably safe to blame your browser cache)

**Comment by trieloff** [comment]
@sjvs beautiful. Thank you!

**Comment by trieloff** [comment]
@sjvs I just did it now. I must have missed the big green button.
